### ISSUE TITLE
ComplexMul function doesn't do the right thing

### ISSUE THREAD

**Issue by otherjason** [mnicely/cufft_examples#1]
This isn't a serious issue because all you're doing is making sure the output of cuFFT and cuFFTDx match, but strictly speaking, the `ComplexMul` function in `cuFFT_vs_cuFFTDx.cu` doesn't do complex multiplication:

```cuda
// Complex multiplication
template<typename T>
__device__ T ComplexMul( T const &a, T const &b ) {
    T c;
    c.x = a.x * b.x;
    c.y = a.y * b.y;
    return ( c );
}
```

Instead, it should be:

```cuda
// Complex multiplication
template<typename T>
__device__ T ComplexMul( T const &a, T const &b ) {
    T c;
    c.x = a.x * b.x - a.y * b.y;
    c.y = a.x * b.y + a.y * b.x;
    return ( c );
}
```

**Comment by mnicely** [comment]
Thanks @otherjason, nice catch! I'll try to get that fixed this week.
