### ISSUE TITLE
builds fail with newest toolkit (11.4.3)

### ISSUE THREAD

**Issue by bHimes** [mnicely/cufft_examples#4]
Hi @mnicely ,

Is cufftdx expected to work with toolkit 11.4.3? Everything seems fine up until 11.3.2 - I did not try in between. Reproduces with sample code.

![image](https://user-images.githubusercontent.com/3077528/132865481-a7d53b70-b52a-4df1-b1dd-241e4ec600a3.png)

**Comment by mnicely** [comment]
You're not the first to experience issues. A bug has been reported and we're working through it now. Sorry for the inconvenience. If there's a workaround I'll let you know.

**Comment by bHimes** [comment]
No worries, good to know it is not something to trouble shoot on my end! (And for completeness, I see I typed 11.3.2 rather than 11.3.1, but I guess that is moot.) Thank you!
