### ISSUE TITLE
support for compute capability 8.6?

### ISSUE THREAD

**Issue by bHimes** [mnicely/cufft_examples#5]
One more question for you @mnicely 

I've been developing on one of our older machines with GV100s, while most of our gear now have A6000's. If I "spoof" the FFT descriptor and tell it I want SM<800>() rather than SM<860>() I can at least compile, but run into memory access errors.

- Looking at the cufftdx code, I see there are mappings from database records from other arch's to 800, so I'm wondering if I could hack in something like that for 860-->800?
- Is your team working on support for CC 8.6?

**Comment by mnicely** [comment]
> If I "spoof" the FFT descriptor and tell it I want SM<800>() rather than SM<860>() I can at least compile, but run into memory access errors.

This is probably due to less resources on sm86. Have you tried using smaller parameters?

> Looking at the cufftdx code, I see there are mappings from database records from other arch's to 800, so I'm wondering if I could hack in something like that for 860-->800?

Not sure

> Is your team working on support for CC 8.6?

Yes

**Comment by bHimes** [comment]
It does seem to fail only for larger sizes, starting at 2048, but that still isn't very big, especially for an RTX A6000. Since your team is working on supporting sm86 devices, I'll plan to continue testing with sm70 and adjust when the time comes. Thank you!
