### ISSUE TITLE
non-power of 2 size transforms.

### ISSUE THREAD

**Issue by bHimes** [mnicely/cufft_examples#6]
Hi @mnicely 

In vs 0.3 of cufftdx, it seems like bluestein's algorithm is used for all non-power of 2 transforms. Adapting the example block_fft_performance.cu to use a workspace, and to print the average time as:
```java
std::cout << "Avg Time [ms_n]: " << time_n / ffts_per_block / cuda_blocks << std::endl; //(inside_repeats * kernel_repeats) << std::endl;

```
I get the following numbers, which show an array of 384 is ~the same as 379 (factors 2^7, 3 and 379 respectively). 

While this is great in terms of generality, having a 384 be > 5x slower than a 512 is a bit unfortunate.

Will there be future support for other radix algorithms, or should I think about implementing this myself?

Thanks! 

Ben

(PS. I'll probably have a few  more questions like this as I move through the project I'm focusing on. Is this forum okay for those?)

```bash
FFT size: 256
FFTs elements per thread: 8
FFTs per block: 1
CUDA blocks: 2560
Blocks per multiprocessor: 32
FFTs run: 2560
Shared memory: 2048
Avg Time [ms_n]: 0.00812642
Time (all) [ms_n]: 20.8036
Performance [GFLOPS]: 5040.35

FFT size: 379
FFTs elements per thread: 8
FFTs per block: 1
CUDA blocks: 320
Blocks per multiprocessor: 4
FFTs run: 320
Shared memory: 8192
Avg Time [ms_n]: 0.085318
Time (all) [ms_n]: 27.3018
Performance [GFLOPS]: 761.043

FFT size: 384
FFTs elements per thread: 8
FFTs per block: 1
CUDA blocks: 320
Blocks per multiprocessor: 4
FFTs run: 320
Shared memory: 8192
Avg Time [ms_n]: 0.0857498
Time (all) [ms_n]: 27.4399
Performance [GFLOPS]: 768.894

FFT size: 512
FFTs elements per thread: 8
FFTs per block: 1
CUDA blocks: 1920
Blocks per multiprocessor: 24
FFTs run: 1920
Shared memory: 4096
Avg Time [ms_n]: 0.0149359
Time (all) [ms_n]: 28.6769
Performance [GFLOPS]: 6170.37
```

**Comment by mnicely** [comment]
You're the second person to mention performance issues for non-po2 sizes. We're looking into it. 

Because you're question are more cuFFTDx focused versus my examples, do you mind moving questions to https://forums.developer.nvidia.com/c/accelerated-computing/gpu-accelerated-libraries/12 and tag with `cufft` & `cufftdx`? 

That way a larger audience can learn from the discussion?

**Comment by bHimes** [comment]
Sure, I'll post over there unless it is more directly related to samples.

- Would it be worthwhile to repost this or previous questions there?
- One reason I posted here was b/c I wasn't sure how publicly (of course this is public too) discussions of cufftdx could be during EA. How close are we to coming out of EA? Any details that shouldn't be discussed yet in that forum?

**Comment by mnicely** [comment]
> Would it be worthwhile to repost this or previous questions there?
Sure! I'll reanswer and it'll help users experience the same issues

>How close are we to coming out of EA? 

Can give out at the moment expect next year.

> Any details that shouldn't be discussed yet in that forum?

You can ask anything :smile: 
It will raise awareness. I just can't answer roadmap questions.
